### ISSUE TITLE
You don't have any example???

### ISSUE THREAD

**Issue by Dongineer** [stockholmux/node_redis-rejson#2]
I just try to use this module. 
But i don't know. how to use this module
I just wrote my sources 
* reuse_client2 = rejson(redis)
* client.json_set('object', '{"foo": "bar", "ans": 42}', (err) => {
      if (err) console.log(err)
    })

I was answered by my system

{ ReplyError: ERR wrong number of arguments for 'json.set' command
  command: 'JSON.SET',
  args: [ 'object', '{"foo": "bar", "ans": 42}' ],
  code: 'ERR' }

How can i resolve this problem. if you know, plz answer my question
I want to some example Plz!!!!!
I'm possible my redis-cli enviorment

**Comment by stockholmux** [comment]
This module is simple bindings module that enables the command set of ReJSON. There are plenty of examples of how ReJSON works on the [ReJSON website](http://rejson.io/).

With your example above I see two small issues:
First bullet: No need to assign it to a variable. Just run the function `rejson(redis);` Ideally before you create your client.
Second bullet: You are missing the (`JSON.SET <key> <path> <json>` is the command signature) or in node.js: `client.json_set('object','.','{"foo": "bar", "ans": 42}',function(err) { ... })`
