### ISSUE TITLE
client.json_set does not override existing data

### ISSUE THREAD

**Issue by c0debreaker** [stockholmux/node_redis-rejson#4]
When I call json_set to update the existing data from previous call, it doesn't update the database.

Here is the code.
```js
client.json_set('allAirlineBuilds', '.', flattenedResponseStr, function(err) {
  console.log(err);
});
```
The `flattenedResponseStr` has new values but the redis database isn't being updated.

So what I did to make it work is added `client.json_del('allAirlineBuilds');`
This works now but is this the proper approach?

```js
client.json_del('allAirlineBuilds');
client.json_set('allAirlineBuilds', '.', flattenedResponseStr, function(err) {
  console.log(err);
});
```

**Comment by stockholmux** [comment]
No, that won't work. I think if you put a callback on `client.json_del('allAirlineBuilds')` it will return an error.  Also, always add a callback for error catching!

I think you just need `client.del('allAirlineBuilds')` instead of the rejson specific command.

**Comment by c0debreaker** [comment]
Sorry, I forgot to get you back on this. the `client.del` worked!

However, the code below is failing too.
```
client.json_set('allAirlineBuilds', '.', flattenedResponseStr, function(err) {
  console.log(err);
});
```
The exact error returned by the callback is
```
{ ReplyError: ERR unknown command 'json.set'
at parseError (/Users/rcamara/repos/sessionmanager/node_modules/redis-parser/lib/parser.js:193:12)
at parseType (/Users/rcamara/repos/sessionmanager/node_modules/redis-parser/lib/parser.js:303:14)
command: 'JSON.SET',
args:
  [ 'allAirlineBuilds',
  '.',
// and so on
```
I tried changing it to `client.json_set` and still the same error.

**Comment by c0debreaker** [comment]
I think I know why. I forgot I built a new redis server. I haven't installed the rejson lib yet. My bad

**Comment by c0debreaker** [comment]
It's working now :), `client.json_set` works again :)
