### ISSUE TITLE
ReplyError: ERR new objects must be created at the root ??

### ISSUE THREAD

**Issue by nikolamakin** [stockholmux/node_redis-rejson#8]
why must be created at the root?

redis.json_set('my-json', '.'+product_id, bejson(newObj), function (err) 

Can't it just do that?

**Comment by stockholmux** [comment]
The changes can't be made at the client object level as it affects the constructor of the client.

**Comment by stockholmux** [comment]
Sorry for closing - I misread your comment question. 

What you probably want to do is something this:
```
redis.json_set('my-json', '.', `{ ${product_id} : ${bejson(newObj)} }`, function (err) { ... });
```

I'm going to still close this as what you're describing is not an issue with the node.js module that adds RedisJSON functionality, but rather the RedisJSON module.

**Comment by nikolamakin** [comment]
hhh, sorry .
