### ISSUE TITLE
retrieving UTF8 instead of escaped unicode

### ISSUE THREAD

**Issue by nelsonlarocca** [stockholmux/node_redis-rejson#9]
I've found that client.json_set(key, ".", value) stores data in Redis server using escaped unicode, so retrieving it loses legibility, but there's no option to get the data "unescaped" .

It would be needed to add an arg to the GET command to enable the NOESCAPE option.
JSON.GET <key> NOESCAPE "."
for instance

comments ?
thanks

**Comment by stockholmux** [comment]
Interesting issue, however it is not actually relevant to this Node.js module - all we are doing here is allowing the commands to work and this is a problem with the [Redis Module RedisJSON](https://oss.redislabs.com/redisjson/). You'll need to take on that repo.

(Closing but please do push forward on the actual module)

**Comment by gaurang12041999** [comment]
How to use `NOESCAPE` with JSON.MGET?
